import RiskMeter from "./RiskMeter";

const percent = (v) => `${Number((v * 100).toFixed(1))}%`;

export default function PredictionResult({ result }) {
  const high = result.Result.toLowerCase().includes("high"); // decided by the API's Result field
  const label = high ? "High Risk" : "Low Risk";
  return (
    <section aria-live="polite" className="clay animate-rise mt-10 p-6 sm:p-10">
      <h2 className="text-lg font-semibold text-muted">Prediction Result</h2>
      <p className={`mt-3 flex items-center gap-3 text-4xl font-extrabold uppercase tracking-tight sm:text-6xl ${high ? "text-bad" : "text-good"}`}>
        <span aria-hidden="true" className="clay-inset flex h-12 w-12 shrink-0 items-center justify-center text-2xl sm:h-14 sm:w-14">{high ? "!" : "✓"}</span>
        {label}
      </p>

      <div className="mt-8 grid gap-5 sm:grid-cols-2">
        <div className="clay-inset p-5">
          <p className="text-sm text-muted">Default Probability</p>
          <p className="mt-1 text-4xl font-bold">{percent(result.default_probability)}</p>
        </div>
        <div className="clay-inset p-5">
          <p className="text-sm text-muted">Model Threshold</p>
          <p className="mt-1 text-4xl font-bold">{percent(result.threshold)}</p>
          <p className="mt-1 text-xs text-muted">The model's configured decision threshold.</p>
        </div>
      </div>

      <div className="mt-8">
        <p className="mb-1 text-sm text-muted">Default Probability</p>
        <RiskMeter probability={result.default_probability} threshold={result.threshold} high={high} />
        <p className="mt-2 text-xs text-muted">The dot is the predicted probability. The white tick marks the decision threshold.</p>
      </div>

      <p className="mt-8 max-w-2xl text-muted">
        Based on the submitted application and the model's configured decision threshold, this application is classified as {label}.
      </p>
      <p className="mt-3 max-w-2xl text-sm text-muted">
        This prediction is generated by a machine learning model and should not be treated as a guaranteed financial decision.
      </p>
      <p className="mt-4 text-xs text-muted">Prediction: {result.default_prediction}</p>
    </section>
  );
}
